use std::fmt::Display;
use std::fs::write;

use crate::paths::*;
use crate::{AnimeEntry, App};

const WARNING_MESSAGE: &str = "# This file was generated by anime-downloader, please do not edit this file unless you know what you're doing\n";

impl App {
    pub fn write_state_file(&self) {
        let state_file_path = get_state_file_path();

        if let Err(_) = write(state_file_path, self.to_string()) {
            make_state();
            self.write_state_file();
        }
    }
}

impl Display for AnimeEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut serialized = String::new();
        serialized.push_str(&format!("[{}]\n", self.get_id()));
        serialized.push_str(&format!(
            "current_episode = {}\n",
            self.get_current_episode()
        ));

        serialized.push('\n');
        write!(f, "{}", serialized)
    }
}

impl Display for App {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut serialized = String::from(WARNING_MESSAGE);

        for entry in self.watch_list.iter() {
            serialized.push_str(&entry.to_string());
        }

        write!(f, "{}", serialized)
    }
}
